//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Notes = new HashSet<Notes>();
        }
    
        public int IdUsers { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> admin { get; set; }
    
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
