//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteManagerServer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Notes = new HashSet<Notes>();
        }
    
        public int idUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
