//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteManagerServer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int idNote { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Creation { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
